main:
	gcc -g main.c prompt.c input.c echo.c commandCall.c changeDir.c ls.c systemCommand.c fProcess.c bProcess.c repeat.c pinfo.c \
	history.c signal.c redirection.c pipe.c replay.c jobs.c sig.c fg.c bg.c